<?php


// !DO NOT EDIT THIS FILE MANUALLY!
// THIS FILE IS AUTOMATICALLY UPDATED BY WP-NUXT

return array(
	"rest"    => array(
		"cache"         => true,
		"menus"         => true,
		"disable_users" => true
	),
	"nuxt"    => array(
		"automatic_generation" => true,
		"node_path"            => "/usr/local/bin/node",
		"nuxt_root_path"       => ""
	),
	"wp_interface" => array(
		"disable_theme_settings" => true,
		"enable_menus" => true,
	),
	"sitemap" => array(
		"enabled" => true,
	),
);